version: 2
updates:
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: daily
    time: "19:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.27
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.38
    - 14.14.41
    - 15.0.0
  - dependency-name: next
    versions:
    - 10.0.5
    - 10.0.6
    - 10.0.7
    - 10.0.8
    - 10.0.9
    - 10.1.1
    - 10.1.2
    - 10.1.3
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "19:30"
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/db"
  schedule:
    interval: daily
    time: "19:30"
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/api"
  schedule:
    interval: daily
    time: "19:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: node
    versions:
    - 15.10.0.pre.alpine
    - 15.11.0.pre.alpine
    - 15.12.0.pre.alpine
    - 15.13.0.pre.alpine
    - 15.14.0.pre.alpine
    - 15.7.0.pre.alpine
    - 15.8.0.pre.alpine
    - 15.9.0.pre.alpine
- package-ecosystem: npm
  directory: "/api"
  schedule:
    interval: daily
    time: "19:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postgraphile-plugin-connection-filter
    versions:
    - 2.1.1
    - 2.2.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: graphql-subscriptions
    versions:
    - 1.2.0
  - dependency-name: helmet
    versions:
    - 4.4.1
- package-ecosystem: docker
  directory: "/client"
  schedule:
    interval: daily
    time: "19:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: node
    versions:
    - 15.10.0.pre.alpine
    - 15.11.0.pre.alpine
    - 15.12.0.pre.alpine
    - 15.13.0.pre.alpine
    - 15.14.0.pre.alpine
    - 15.7.0.pre.alpine
    - 15.8.0.pre.alpine
    - 15.9.0.pre.alpine
