version: '3.7'

services:
  client-dev:
    container_name: client-dev
    build:
      context: ./client
      dockerfile: Dockerfile.development
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true