version: "3.7"

services:
  db:
    container_name: db
    restart: always
    image: db
    build:
      context: ./db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    stdin_open: true
    tty: true

volumes:
  db: