version: "3.7"

services:
  db:
    container_name: db
    restart: always
    image: db
    build:
      context: ./packages/backend/db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    stdin_open: true
    tty: true

  graphql:
    container_name: graphql
    restart: always
    image: graphql
    build:
      context: ./packages/backend/graphql
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 5433:5433
    command:
      [
        "--connection",
        "${DATABASE_URL}",
        "--port",
        "5433",
        "--schema",
        "public",
        "--default-role",
        "trackportfolio_anonymous",
        "--jwt-secret",
        "${JWT_SECRET}",
        "--jwt-token-identifier",
        "public.jwt_token",
        "--append-plugins",
        "postgraphile-plugin-connection-filter",
        "--cors",
      ]

volumes:
  db: