name: Test Client

on:
  push:
    paths:
      - 'client/**'

jobs:
  build-and-test-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "13.10"

      - name: Install dependencies
        run: |
          cd client
          yarn --frozen-lockfile

      - name: Test local build
        run: |
          cd client
          yarn build
