name: build-and-test-client

on:
    push:
      paths:
        - 'client/**'

    pull_request:
      paths:
        - 'client/**'     

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "13.10"

      - name: Install yarn
        run: |
          cd client
          yarn --frozen-lockfile

      - name: Run unit tests
        run: |
          cd client
          yarn test
