name: Deploy Client

on:
  push:
    paths:
      - 'client/**'
      - '.github/**'
#     branches:
#       - master

jobs:
  build-and-deploy-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 13.10
        uses: actions/setup-node@v1
        with:
          node-version: "13.10"

      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: lynchynz/trackportfol.io/client-prod
          registry: docker.pkg.github.com
          username: ${{ secrets.GIT_USERNAME }}
          password: ${{ secrets.GIT_TOKEN }}
          dockerfile: client/Dockerfile.deploy
          tags: latest

      - name: Deploy package to server
        uses: appleboy/ssh-action@master
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_KEY }}
          port: ${{ secrets.PROD_PORT }}
          envs: GIT_USERNAME, GIT_TOKEN
          script: |
            docker stop client-prod
            docker rm client-prod
            docker login docker.pkg.github.com -u $GIT_USERNAME -p $GIT_TOKEN
            docker pull docker.pkg.github.com/lynchynz/trackportfol.io/client-prod:latest
            docker run -dit --name client-prod -p 1337:1337 docker.pkg.github.com/lynchynz/trackportfol.io/client-prod:latest