name: Deploy GraphQL

on:
  push:
    paths:
      - 'backend/graphql/**'
    branches:
      - master

jobs:
  deploy-graphql:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 13.10
        uses: actions/setup-node@v1
        with:
          node-version: "13.10"

      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          PROTECTED_FILES_PASSPHRASE: ${{ secrets.PROTECTED_FILES_PASSPHRASE }}
        with:
          name: dan-lynch/trackportfol.io/graphql
          registry: docker.pkg.github.com
          username: ${{ secrets.GIT_USERNAME }}
          password: ${{ secrets.GIT_TOKEN }}
          envs: PROTECTED_FILES_PASSPHRASE
          dockerfile: backend/graphql/Dockerfile.deploy
          tags: latest

      - name: Deploy package to server
        uses: appleboy/ssh-action@master
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_KEY }}
          port: ${{ secrets.PROD_PORT }}
          envs: GIT_USERNAME, GIT_TOKEN
          script: |
            docker stop graphql
            docker rm graphql
            docker login docker.pkg.github.com -u $GIT_USERNAME -p $GIT_TOKEN
            docker pull docker.pkg.github.com/dan-lynch/trackportfol.io/graphql:latest
            docker run -dit --name graphql -p 5433:5433 docker.pkg.github.com/dan-lynch/trackportfol.io/graphql:latest