name: Deploy API

on:
  push:
    paths:
      - 'backend/graphql/**'
    # branches:
    #   - master

jobs:
  deploy-graphql:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 13.10
        uses: actions/setup-node@v1
        with:
          node-version: "13.10"

      - name: Deploy API changes to server
        uses: appleboy/ssh-action@master
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          PROTECTED_FILES_PASSPHRASE: ${{ secrets.PROTECTED_FILES_PASSPHRASE }}
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_KEY }}
          port: ${{ secrets.PROD_PORT }}
          envs: GIT_USERNAME, GIT_TOKEN, PROTECTED_FILES_PASSPHRASE
          script: |
            git fetch --all
            git reset --hard origin/master
            env PASSPHRASE=$PROTECTED_FILES_PASSPHRASE sh ./decrypt_protected_files.sh
            docker-compose -f docker-compose.backend.yml down
            docker-compose -f docker-compose.backend.yml up -d --build