name: Deploy API

on:
  push:
    paths:
      - 'api/**'
      - 'db/**'
      - 'client/**'

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy API changes to server
        uses: appleboy/ssh-action@master
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          PROTECTED_FILES_PASSPHRASE: ${{ secrets.PROTECTED_FILES_PASSPHRASE }}
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_KEY }}
          port: ${{ secrets.PROD_PORT }}
          envs: GIT_USERNAME, GIT_TOKEN, PROTECTED_FILES_PASSPHRASE
          script: |
            docker system prune --force